name: CI Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Run Linting
      run: flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Run Tests
      run: pytest tests/
